apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-dev
  namespace: cluster-core
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1h
  targetNamespace: observability
  releaseName: loki-dev

  chart:
    spec:
      chart: loki
      version: 6.36.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: cluster-core

  install:
    timeout: 20m0s
    crds: Skip
    disableWait: true
    waitForJobs: false
    remediation:
      retries: 3
      remediateLastFailure: true

  upgrade:
    timeout: 20m0s
    crds: Skip
    disableWait: true
    waitForJobs: false
    remediation:
      retries: 3
      remediateLastFailure: true

  test:
    enable: false

  values:
    global:
      extraEnv:
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: loki-azure-storage
              key: AZURE_STORAGE_KEY
      extraEnvFrom:
        - secretRef:
            name: loki-azure-storage
      extraArgs:
        - "-config.expand-env=true"

    loki:
      auth_enabled: false

      # ✅ server should be top-level under loki
      server:
        log_level: debug

      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 72h

      readinessProbe:
        httpGet:
          path: /ready
          port: http-metrics
        initialDelaySeconds: 30
        timeoutSeconds: 5
        periodSeconds: 10
        failureThreshold: 10

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: azure
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      storage:
        type: azure
        azure:
          accountName: ecpcn3devlokistorage
          accountKey: null
          connectionString: null
          useManagedIdentity: false
          endpointSuffix: blob.core.chinacloudapi.cn
        bucketNames:
          chunks: "lokinonprod"
          ruler: "lokinonprodruler"
          admin: "lokinonprodadmin"

      storage_config:
        azure:
          account_name: "ecpcn3devlokistorage"
          account_key: "${AZURE_STORAGE_ACCOUNT_KEY}"
          container_name: "lokinonprod"
          endpoint_suffix: "blob.core.chinacloudapi.cn"

        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          resync_interval: 5m
          cache_ttl: 24h

      ingester:
        chunk_encoding: snappy

      querier:
        max_concurrent: 1

    deploymentMode: Distributed

    ingester:
      replicas: 3
      persistence:
        enabled: true
        size: 10Gi
      zoneAwareReplication:
        enabled: false
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability
      resources:
        requests:
          cpu: "4500m"
          memory: "8Gi"
        limits:
          cpu: "8000m"
          memory: "16Gi"

    querier:
      replicas: 3
      maxUnavailable: 2
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    queryFrontend:
      replicas: 2
      maxUnavailable: 1
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    queryScheduler:
      replicas: 2
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    compactor:
      replicas: 1
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    indexGateway:
      replicas: 2
      maxUnavailable: 1
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    ruler:
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    bloomPlanner:
      replicas: 0

    bloomBuilder:
      replicas: 0

    bloomGateway:
      replicas: 0

    backend:
      replicas: 0

    read:
      replicas: 0

    write:
      replicas: 0

    singleBinary:
      replicas: 0
      server:
        http_listen_port: 3100

      extraPorts:
        - name: http-metrics
          port: 3100
          targetPort: 3100

      querier:
        ingester:
          ring:
            store: memberlist

      storage:
        type: azure
        bucketNames:
          chunks: lokinonprod
          ruler: lokinonprod
          admin: lokinonprod
          index: lokinonprod

    gateway:
      enabled: true
      service:
        type: ClusterIP
      basicAuth:
        enabled: false
        username: lokiadmin
        password: lokiadmin

    chunksCache:
      enabled: true
      defaultValidity: 24h
      resources:
        requests:
          cpu: 125m
          memory: 8Gi
        limits:
          cpu: 500m
          memory: 8Gi
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    resultsCache:
      enabled: true
      defaultValidity: 24h
      resources:
        requests:
          cpu: 250m
          memory: 9830Mi
      tolerations:
        - effect: NoSchedule
          key: bakery.io/app
          operator: Equal
          value: observability

    writeDedupeCache:
      enabled: true
      defaultValidity: 24h
      resources:
        requests:
          cpu: 250m
          memory: 9830Mi
